

```{r include = FALSE}
library(tidyverse)
library(janitor)
library(purrr)
library(readxl)
library(dplyr)
source("functions.R")
```

# Australia

```{r}
aus <- 
readxl::read_excel("../data/phenotypes/other countries/Australia.xlsx") %>%
  clean_names() %>% 
  dplyr::select(year_of_release, location, variety, grain_kg_ha) %>% 
  group_by(location, variety) %>% 
  nest() %>% 
  mutate(data = map(data, ~.x %>% rowid_to_column("R")
                      )
         ) %>% 
  unnest(cols = c("data")) %>% 
  
  rename_all(~c("E", "G","R", "YOR", "GY")) %>% 
  plasticity3(G, "GY") %>% 
  mutate(Region = "Australia") %>% 
  dplyr::select(Region, G, YOR, E, R, GY, PP_GY) %>% 
  mutate_at(vars(G, E, R, Region), ~as.factor(.)) %>% 
  mutate(.,
         YOR = as.integer(YOR), 
         GY = as.double(GY)/1000, 
         PP_GY = as.double(PP_GY)
         )
```

# Canada

```{r}
# Year of release
yor <- read.csv("../data/phenotypes/other countries/ARVAC_YOR_spring.csv") %>% 
  mutate(G = str_replace_all(G, " VB", ""), 
         G = str_replace_all(G, "KWS ", ""),
         G = str_replace_all(G, "CDC ", ""),
         G = str_replace_all(G, "AAC ", ""),
         G = str_replace_all(G, "AC ", ""), 
         G = str_replace_all(G, "SY ", ""), 
         G = str_replace_all(G, " ", "")
         )
```

```{r}
# Spring wheat Manitoba
mcvet.s <- 
  read_excel("../data/phenotypes/other countries/MCVET.xlsx", sheet = "Spring wheat - yield") %>%
  clean_names() %>% 
  mutate(E = paste0(location, "_", year), 
         kgha = kgha/1000) %>% 
  dplyr::select(name, E,rep, kgha) %>% 
  rename_all(~c("G","E","R", "GY")) %>% 
  group_by(G) %>% 
  nest() %>% 
  mutate(n_env = data %>%  map_dbl(~.x %>% 
                                select(E) %>% 
                                unique() %>% 
                                nrow(.)
                                ),
         
         G = toupper(G), 
         G = str_replace_all(G, "_", " "), 
         G = str_replace_all(G, " VB", ""), 
         G = str_replace_all(G, "KWS ", ""),
         G = str_replace_all(G, "CDC ", ""),
         G = str_replace_all(G, "AAC ", ""), 
         G = str_replace_all(G, "AC ", ""),
         G = str_replace_all(G, "SY ", ""),
         G = str_replace_all(G, " ", ""), 
         
         G = case_when(G == "VRMORRIS" ~ "MORRIS", T~G),
         Region = "Manitoba"
         ) %>% 
  filter(n_env >= 25) %>% 
  unnest(c(data)) %>% 
  ungroup() %>% 
  left_join(yor, by = join_by(G))
```

```{r}
# Spring wheat Alberta
arvac.s <- 
  read_excel("../data/phenotypes/other countries/ARVAC.xlsx", sheet = "plot_data_yield", range = "A1:K31956") %>% 
  filter(crop == "SPRING WHEAT") %>% 
  dplyr::select(location,year, rep, selccode, dataval) %>% 
  transmute(E = paste0(location, "_", year), 
            R = rep, 
            G = selccode, 
            GY = dataval/1000) %>% 
  group_by(G) %>% 
  nest() %>%
  mutate(n_env = data %>%  map_dbl(~.x %>%
                                select(E) %>%
                                unique() %>%
                                nrow(.)
                                ),
         G = str_replace_all(G, " VB", ""), 
         G = str_replace_all(G, "KWS ", ""),
         G = str_replace_all(G, "CDC ", ""),
         G = str_replace_all(G, "AAC ", ""),
         G = str_replace_all(G, "AC ", ""), 
         G = str_replace_all(G, "SY ", ""), 
         G = str_replace_all(G, " ", ""), 
         Region = "Alberta"
         ) %>%
  filter(n_env >= 25) %>%
  unnest(c(data)) %>%
  ungroup() %>%
  left_join(yor,by = join_by(G))

```

```{r}
canada.s <- 
rbind(mcvet.s, arvac.s) %>% 
  plasticity3(G, "GY") %>% 
  dplyr::select(Region, G, YOR, E, R, GY, PP_GY) %>% 
  mutate_at(vars(G, E, R, Region), ~as.factor(.)) %>% 
  mutate(.,
         YOR = as.integer(YOR), 
         GY = as.double(GY), 
         PP_GY = as.double(PP_GY)
         )
```

# Argentina

```{r warning=FALSE}
arg <- 
read_excel("../data/phenotypes/other countries/RET full 2005-2022 Nicolas Giordano.xlsx", range = "A3:R14771") %>% 
  janitor::clean_names() %>%
  pivot_longer(cols = c(rep1:rep3), 
               names_to = "R",
               values_to = "GY") %>% 
  mutate(E = paste0(localidad_pea, "_", ano_pea)) %>% 
  dplyr::select(E,epoca_pea, cultivar_pea, inscripcion, R, GY, gc) %>% 
  rename_all(~c("E","EP", "G", "YOR", "R", "GY", "GC")) %>% 
  # rep 3 miramar 2007 is all zeros
  filter(E != "Miramar, BA_2007" & R != "rep3") %>% 
  # epoca 1 CL y 3 CC unicamente
  filter(EP %in% c(1,3)) %>% 
  #group_by(EP) %>%
  nest() %>% 
  mutate(data = map(.x = data, 
                     ~plasticity3(.x, G, "GY")
                     )) %>% 
  unnest() %>% 
  group_by(G,EP) %>% 
  nest() %>% 
  mutate(n_env = data %>%  map_dbl(~.x %>% 
                                select(E) %>% 
                                unique() %>% 
                                nrow(.)
                                )
         ) %>% 
  filter(n_env >= 25) %>% 
  unnest() %>% 
  ungroup() %>% 
  mutate(Region = "Argentina", 
         R = str_replace(R, pattern = "rep",replacement =  "")) %>% 
  dplyr::select(Region, G, YOR, E, R, GY, PP_GY, EP) %>% 
  mutate_at(vars(G, E, R, Region), ~as.factor(.)) %>% 
  mutate(.,
         YOR = as.integer(YOR), 
         GY = as.double(GY)/1000, 
         PP_GY = as.double(PP_GY)
         ) %>% 
  select(-EP)
arg %>% 
  ggplot(aes(x = PP_GY, y = GY))+
  geom_point(shape = 21, alpha = 0.2, fill = "black")


```

# Central Great Plains

```{r}
dataYOR <- read_csv("../data/phenotypes/var_traits_final_YOR.csv",
                    show_col_types = F) %>% 
  mutate(.,
         G = str_replace_all(G,"_", " " ),
         G = str_replace_all(G,"'", " " ), 
         G = case_when(G == "SNOWMASS 2.0"~"SNOWMASS 2", T~G)) 

central_great_plains <- 
read_csv("../data/phenotypes/vpt_all_final.csv") %>%
  unique() %>% 
  mutate(.,
         G = str_replace_all(G,"'", " " ), 
         G = case_when(G == "SNOWMASS 2.0"~"SNOWMASS 2", T~G)
         ) %>% 
  dplyr::select(G, E, PP_GY, GY) %>% 
  drop_na() %>% 
  # Get the number of replicates
  group_by(G, E) %>% 
  nest() %>% 
  mutate(R = map_dbl(data, ~nrow(.))) %>% 
  unnest(cols = data) %>% 
  mutate(.,
         Region = "Central Great Plains") %>% 
  # Join YOR
  full_join(dataYOR[,-2]) %>% 
  dplyr::select(Region, G, YOR, E, R, GY, PP_GY) %>% 
  
  mutate_at(vars(G, E, R, Region), ~as.factor(.)) %>% 
  mutate(.,
         YOR = as.integer(YOR), 
         GY = as.double(GY), 
         PP_GY = as.double(PP_GY)
         )
```

# Uruguay

```{r}
uru <- read_excel("../data/phenotypes/other countries/INIA_Uruguay.xlsx", sheet = "BD")
uru <- 
uru[, c("Año de Siembra","Localidad", "Último_Nombre", "Rendimiento SF")] %>% 
  rename_all(~c("Y","S", "G", "GY" )) %>% 
  mutate(E = paste0(S, "_", Y))

nenv <-
uru %>% 
  group_by(G) %>% 
  count() %>% 
  filter(n>=25)


uru <- 
uru %>% 
  filter(G %in% nenv$G) %>% 
  plasticity3(G, "GY") %>% 
  select(-c(Y, S)) %>% 
  mutate(R = NA)
yor_uru <- 
uru %>% 
  select(G) %>% 
  unique() %>% 
  cbind(YOR = c(2006,2007, 2007, 2013, 2008, 2013, 2013, 1997, 2000, 2011, 2011, 2014, 2016, 2017, 2018, 2018, 2021 ))

uru <- uru %>% 
  mutate(Region = "Uruguay", 
         GY = GY/1000) %>% 
  full_join(yor_uru, by = join_by(G))
```

# United Kingdom

```{r}
years <- excel_sheets("../data/phenotypes/other countries/Reccomended Lists UK.xlsx")[-c(14,13, 19:22)]


uk_all <- data.frame()



for (i in 1:length(years)){
  
  year <- years[i]
  
  uk_sites <- read_excel("../data/phenotypes/other countries/Reccomended Lists UK.xlsx", 
                         col_names = F,
                         sheet = year
                         )[1:2,-c(1,2)] %>% 
  mutate(site = c("Site", "County")) %>% 
  pivot_longer(cols = -site) %>% 
  pivot_wider(values_from = value, names_from = site) %>% 
  mutate(SITE = paste0(Site,"_",County))

  uk_sites <- paste0(uk_sites$SITE, seq(1,length(uk_sites$SITE)))
  
  uk <- 
    read_excel("../data/phenotypes/other countries/Reccomended Lists UK.xlsx", 
               col_names = F, 
               sheet = year
               )[-c(1,2),] %>% 
    #dplyr::select(-...1)  %>% 
    rename_all(~c("G","G1", uk_sites)) %>% 
    pivot_longer(cols = -c("G", "G1"), 
                 names_to = "S",
                 values_to = "GY") %>% 
    mutate(Y = as.integer(year), 
           E = paste0(S, "_", Y), 
           GY = str_replace(GY, "-", ""), 
           GY = as.double(GY)
           ) %>% 
    dplyr::select(E,Y,G,G1,GY)
  
  print(year)
  
  uk_all <- rbind(uk_all, uk)
  
}

uk_out <- uk_all %>% 
  group_by(G1) %>% 
  transmute(
         YOR = as.double(min(Y)), 
         Region = as.factor("United Kingdom"), 
         G = as.factor(G1), 
         E = as.factor(E), 
         R = as.factor(NA),
         GY = GY
         ) %>% 
  plasticity3(G, "GY") %>% 
  ungroup() %>% 
  select(-G1)


uk_all %>% 
  mutate(.by = "G", 
         YOR = min(Y)) %>% 
  
  plasticity3(G, "GY") %>% 
  # summarise(.by = c("G", "YOR"), 
  #           BLUP = mean(GY, na.rm=T)
  #           ) %>% 
  ggplot(aes(x = PP_GY, y = GY))+
  geom_point()
  
test <- 
uk_all %>%
  dplyr::select(G, E) %>% 
  unique() %>% 
  group_by(G) %>% 
  count() %>% 
  filter(n>25)

test <- uk_all %>% 
  select(G, G1) %>% 
  unique() %>% 
  mutate(G = str_replace_all(G, ' \\(C\\)', "")) %>% 
  unique()


write.csv(test, "../data/phenotypes/guido_year_of_release.csv", row.names = F)
```



# Bind all datasets in a single one

```{r}
# I excluded Australian data as the data does not have the same structure. Is a historic lines trial not testing network. 
data <- rbind(canada.s, central_great_plains, arg, uru, uk_out) %>% 
  drop_na(Region) %>% 
  mutate(.,
         GY = case_when(GY <0~NA_real_, T~GY),
         # Get a unique identifier for each cultivar
         G1 = as.factor(paste0("G", as.numeric(as.factor(paste0(G))))), 
         E1 = as.factor(paste0("E",as.numeric(E)))
         )

write_csv(data, "../data/phenotypes/data_all_countries.csv") 


ggplot(data = data, aes(x = GY))+
  facet_wrap(~Region)+
  geom_density()
```

# Test for minimum number of environments

```{r}
dfEnv <- 
  uru %>% 
  filter(G == "BAGUETTE PREMIUM 11")

 

sigmaOut <- c()
nOut <- c()


for (n in 2:68){
  set.seed(123)
  #n <- 20
  s <- sample(seq(1,68,1), n, replace = F)
  sigma_g <- var(as.vector(dfEnv[s,2])$GY, na.rm = T)
  
  sigmaOut <- c(sigmaOut, sigma_g)
  nOut <- c(nOut, n)
  
}

ggplot()+
  geom_point(aes(x = nOut, y = sigmaOut))+
  theme_bw()+
  labs(x = "Number of environments", y = "Genotypic variance")
```

```{r}
t <- 
central_great_plains %>% 
  dplyr::select(G, E) %>% 
  unique() %>% 
  group_by(G) %>% 
  count()

dfEnv <- central_great_plains %>% 
  ungroup() %>% 
  filter(G == "JAGGER")

sigmaOut <- c()
nOut <- c()


for (n in 2:1751){
  set.seed(123)
  #n <- 20
  s <- sample(seq(1,1751,1), n, replace = F)
  sigma_g <- var(as.vector(dfEnv[s,"GY"])$GY, na.rm = T)
  
  sigmaOut <- c(sigmaOut, sigma_g)
  nOut <- c(nOut, n)
  
}

sigmaOut
nOut

var(central_great_plains$GY, na.rm = T)

ggplot()+
  geom_point(aes(x = nOut, y = sigmaOut/var(central_great_plains$GY, na.rm = T)))+
  theme_bw()+
  scale_x_continuous(limits = c(0,500))+
  geom_vline(xintercept = 25)+
  labs(x = "Number of environments", y = "Yield Plasticity")
```


