---
title: "GWAS GAPIT"
format: html
editor: visual
---

# Packages

```{r include = FALSE}
library(tidyverse)
library(GAPIT)
library(gwaspr)

library(extrafont)
loadfonts(device = c("all", "pdf", "postscript", "win"))
`%nin%` <- Negate(`%in%`)
# Custom ggplot theme to make pretty plots
# Get the font at https://fonts.google.com/specimen/Jost
theme_nice <- function() {
  theme_minimal(base_family = "Jost") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(family = "Jost", face = "bold"),
          axis.title = element_text(family = "Jost Medium"),
          strip.text = element_text(family = "Jost", face = "bold",
                                    size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA))
}


```

# Data

```{r message = FALSE}
# Reaction norms of environmental covariates
reaction_norm_ec <- readRDS("../output/model output/Reaction norm all weather_GY.RData")
reaction_norm_gye <- readRDS("../output/model output/Reaction norm GYE_GY.RData")

data <- read_csv("../data/phenotypes/data_all_countries.csv") %>%
  # Central Great Plains Only
  filter(Region == "Central Great Plains") %>% 
  dplyr::select(Region, G, G1, PP_GY, BLUP) %>% 
  unique() %>% 
  # String operations to merge with genotype data
  mutate(.,
         G = str_replace_all(G, " ", "_"), 
         G = str_replace_all(G, "/", "-"), 
         G = str_replace_all(G, "'", ""), 
         G = str_replace_all(G, "SNOWMASS_2.0", "SNOWMASS_2")
         ) %>% 
  # These cultivars don't have marker data
  filter(G %nin% c("AGSECO_7853", "CSU_BLEND09", "JAG,2137", "JEI_110",
                   "KALVESTA", "OK05312", "SY_LLANO","TAM_113","TONKAWA")) %>% 
  drop_na(BLUP, PP_GY) %>% 
  left_join(reaction_norm_ec, by = join_by(G1)) %>% 
  left_join(reaction_norm_gye, by = join_by(G1))
```

## Genotype

```{r message = FALSE}
G <- data.table::fread("../data/genotypes/KSL2023-Nico-GBS.Filtered.bi.MLC80.maf05.mono.recode.FromVCF.hmp.txt", header = FALSE)

names <- 
G[1,12:251] %>% 
  pivot_longer(cols = everything(), 
               names_to = "var_no",
               values_to = "G") %>% 
  right_join(data[,2:3],by = join_by("G")) %>% 
  drop_na()

#Save genotype IDs to file
#write.csv(names, "../data/genotypes/genotypesID.csv", row.names = F)


G1 <- 
  G %>% 
  dplyr::select(paste0("V", 1:11),names$var_no) %>% 
  #rename_all(~paste0("V", 1:230)) %>% 
  mutate(.,
         V1 = case_when(V1 == "rs#"~"rs",T~V1), 
         V6 = case_when(V6 == "assembly#"~"assembly",T~V6)
         ) %>% 
  as.data.frame()

G1[1,] <-  unlist(c(as.vector(G1[1,1:11]) , names$G1))

#Save genotype to csv file
#write.csv(G1, "../data/genotypes/MLC80.maf05_hmp.csv", row.names = F)
```

# Phenotype

```{r message = FALSE}
# Two phenotypes together
Y <- data[,3:16] %>% 
  as.data.frame()
```

# Model

```{r}
models <- c("GLM", "MLM", "MLMM", "FarmCPU", "BLINK")

GWAS <- GAPIT(
  Y = Y,
  G = G1,
  PCA.total = 7,
  model = models)
```
