---
title: "23. Plasticity"
format: html
editor: visual
---

```{r include = FALSE, message = FALSE}
library(tidyverse)
library(lme4)
library(marginaleffects)
library(extrafont)
loadfonts(device = c("all", "pdf", "postscript", "win"))
`%nin%` <- Negate(`%in%`)
# Custom ggplot theme to make pretty plots
# Get the font at https://fonts.google.com/specimen/Jost
theme_nice <- function() {
  theme_minimal(base_family = "Jost") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(family = "Jost", face = "bold"),
          axis.title = element_text(family = "Jost Medium"),
          strip.text = element_text(family = "Jost", face = "bold",
                                    size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA))
}
```

```{r}
data <- read_csv("../data/phenotypes/data_all_countries.csv") 

mod_gamma <- readRDS("../output/model output/mod_gamma_GxE_BLUPs.RData")

yenv <- 
  data[,c("Region","G1","E1", "YOR","GY", "PP_GY", "BLUP")] %>% 
  left_join(coef(mod_gamma)$E1 %>% 
              rownames_to_column("E1"), 
            by = join_by(E1)) %>% 
  mutate(.,
         GYE =  exp(as.double(`(Intercept)`))) %>% 
  dplyr::select(-`(Intercept)`) %>% 
  # Filter only Central Great Plains Region
  filter(Region == "Central Great Plains") %>% 
  # Add reps
  nest(.by = c("G1", "E1")) %>% 
  mutate(data = map(data, ~.x %>% rowid_to_column("R"))) %>% 
  unnest(data)

```

```{r}
env <- readRDS("../data/environment/weather_summaries_daymet.RData")

yenv1 <- 
  full_join(yenv, env, by = join_by(E1))
```

# Calculate plasticity as the slope of a reaction norm

```{r}
env_rn <- 
yenv1 %>% 
  dplyr::select(G1, GY, PP_CP:VPD_GF) %>% 
  #filter(G1 %in% unique(yenv1$G1)[1:10]) %>% 
  pivot_longer(cols = c(PP_CP:VPD_GF)) %>%
  drop_na(value, GY) %>% 
  nest(.by = c("name")) %>% 
  # reaction norm
  mutate(mod = map(data, ~lm(GY ~ value*G1, data = .x)), 
         slopes = map(mod, function(mod){
                     slopes(mod, 
                            newdata = datagrid(value = unique(mod$model$value), G1 = mod$xlevels$G1),
                            variables = "value"
                            )  
           }),
         slope = map(slopes, ~.x %>% 
                       dplyr::select(G1, estimate) %>% 
                       mutate(estimate = round(estimate,5)) %>% 
                       unique()
         )) %>% 
  dplyr::select(-c(mod, slopes, data)) %>% 
  unnest(slope) %>% 
  pivot_wider(names_from = name,values_from = estimate)


saveRDS(env_rn, "../output/model output/Reaction norm all weather_GY.RData")


```

```{r}
env_rn <- 
yenv1 %>% 
  dplyr::select(G1, GY, GYE) %>% 
  #filter(G1 %in% unique(yenv1$G1)[1:10]) %>% 
  pivot_longer(cols = c(GYE)) %>%
  drop_na(value, GY) %>% 
  nest(.by = c("name")) %>% 
  # reaction norm
  mutate(mod = map(data, ~lm(GY ~ value*G1, data = .x)), 
         slopes = map(mod, function(mod){
                     slopes(mod, 
                            newdata = datagrid(value = unique(mod$model$value), G1 = mod$xlevels$G1),
                            variables = "value"
                            )  
           }),
         slope = map(slopes, ~.x %>% 
                       dplyr::select(G1, estimate) %>% 
                       mutate(estimate = round(estimate,5)) %>% 
                       unique()
         )) %>% 
  dplyr::select(-c(mod, slopes, data)) %>% 
  unnest(slope) %>% 
  pivot_wider(names_from = name,values_from = estimate)


saveRDS(env_rn, "../output/model output/Reaction norm GYE_GY.RData")

```


```{r fig.width = 15, fig.height=15}
env_rn %>% 
ggplot(aes(x = value, y = GY, fill = G1))+
  #geom_point(alpha = .01, size=2, shape=21)+
  geom_line(aes(x = value, y = preds, color = G1))+
  facet_wrap(~name, scales = "free_x")+
  guides(fill = "none", color = "none")+
  theme_nice()


```
