---
title: "Untitled"
author: "Nicolas Giordano"
date: "2024-05-30"
output:
  word_document: default
  html_document: default
---

# Model 1

Calculate BLUPs, random effects G

$$y_{i} \sim \Gamma(\mu_{i}, \phi)$$

$$log(\mu_i) \sim \eta_{i}$$

$$\eta_{i} \sim \mathbf{Z_G} \mathbf{\beta_G} + \mathbf{Z_E} \mathbf{\beta_E} + \mathbf{Z_{GE}} \mathbf{\beta_{GE}}$$


Here, $y_i$ is the $ith$ yield observation $(i:1,2,...,n)$ with expected value $\mu_i$ which is linked to the linear predictor $\eta_i$ through a log-link function. Thus, the process model for $\eta_i$ includes $\mathbf{Z_G}$ which is an $n \mathbf{x} m_1 (m_1:1,2,...,num~gen)$ matrix of genotypes ($G$), while $\beta_G$ is a vector of length $m_1$ of random effects for $G$ or BLUPs. Similarly,  $\mathbf{Z_E}$ is a matrix of size $n \operatorname{x} m_2 (m_2:1,2,...,num~gen)$ representing the incidence of each environment ($E$). $\beta_E$ is a vector of length $m_2$ containing the $E$ random effects. Finally, $\mathbf{Z_{GE}}$ is a matrix of size $n \operatorname{x} m_3 (m_3=m_1m_2)$ for $\operatorname{GxE}$ random effects and $\beta_{GE}$ the corresponding random effects for $\operatorname{GxE}$ interaction.

To explore the genetic trends over time of grain yield per se and yield plasticity we defined the following models independently for each region:

$$y_{G} \sim \Gamma(\mu_{G}, \phi)$$
$$log(\mu_G) \sim \eta_{G}$$

$$\eta_{G} \sim \beta_{0} + \beta_{1}YOR_G$$

where $y_G$ represents the $Gth$ $(G:1,2,...,G)$genotype-specific yield BLUPs ($\beta_G$) or yield plasticity ($\operatorname{PP}_G$) within a given region of interest. The expected value of the response variable $y_i$ is $\mu_i$ which is linked to the linear predictor $\eta_i$ through a log-link function.


$$y_{G} \sim \operatorname{ALD}(\mu_{G}, \phi, \tau)$$
$$log(\mu_G) \sim \eta_{G}$$

$\tau = 0.90$

$$\eta_{G} \sim \beta_{0} + \beta_{1}YOR_G + \beta_{2}YOR_G^2$$

$$y_{G} \sim \operatorname{ALD}(\mu_{G}, \phi, \tau)$$


$$log(\mu_G) \sim \eta_{G}$$

$$\eta_{G} \sim \beta_{0} + \beta_{1}\sigma_{PP}$$

Linear plateau

$$
\eta_{G} \sim
\begin{cases} 
 \beta_{0} + \beta_{1}\sigma_{PP} ~~~~~if~\sigma_{PP} \geq c,\\
 \beta_{0} + \beta_{1}c ~~~~~otherwise. 
\end{cases}
$$
# Model 2





