



```{r setup warning = F, message = F}
library(tidyverse)
library(extrafont)

loadfonts(device = c("all", "pdf", "postscript", "win"))
`%nin%` <- Negate(`%in%`)
# Custom ggplot theme to make pretty plots
# Get the font at https://fonts.google.com/specimen/Jost
theme_nice <- function() {
  theme_minimal(base_family = "Jost") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(family = "Jost", face = "bold"),
          axis.title = element_text(family = "Jost Medium"),
          strip.text = element_text(family = "Jost", face = "bold",
                                    size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA))
}

clrs <- MetBrewer::met.brewer("Java")
`%nin%` <- Negate(`%in%`)
```

```{r}
ld <- read.table("../../data/genotypes/Tassel_LD_output.txt", header = T) %>%  
  select(Dist_bp, R.2) %>% 
  janitor::clean_names() %>% 
  mutate_all(~as.numeric(.)) %>% 
  drop_na()
```

```{r}
library(nlraa)

mod <- nls(r_2 ~ SSexpf(dist_bp, a, c), data = ld)

preds <- data.frame(dist_bp = ld$dist_bp, preds = predict(mod)) 

plot(ld$dist_bp, ld$r_2)
lines(ld$dist_bp, predict(mod), col = "red", lwd = 2 )
```


```{r}
ldt <- 
  preds %>% 
  #distance at R2 == 0.3
  filter(dist_bp == 2579160	) %>% 
  pull(dist_bp)

pld <- 
ld %>% #[sample(1:nrow(ld), 100000),] %>% 
  ggplot(aes(x= dist_bp, y = r_2))+
  geom_point(shape = 21, alpha = 0.006, fill = "grey30")+
  geom_line(data = preds, aes(x = dist_bp, y = preds), linewidth = 1, color = "red")+
  geom_vline(aes(xintercept = ldt), linewidth = 1, linetype = "dashed", color = "red")+
  labs(y = expression("R"^2), x = "Distance (base pairs)")+
  theme_nice()+
  theme(plot.background = element_rect(fill = "white"))+
  scale_x_continuous(limits = c(0, 1e8))

ggsave(plot = pld, filename = "../../output/plots/paper/LD_results.png", width = 5, height = 5)
```






